language: node_js
node_js:
- 12
cache:
  yarn: true
install:
- yarn --frozen-lockfile
before_script:
- curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64
  > ./cc-test-reporter
- chmod +x ./cc-test-reporter
- "./cc-test-reporter before-build"
script:
- yarn test:cov
- yarn test:e2e --forceExit
after_script:
- "./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT"
deploy:
  provider: heroku
  api_key:
    secure: WyQq2LlCfW4oY5/W3oyE0eUFmioh+g0sHo1/DlA6OHETgnmKRluootJ2S2ClgVCpTZw1OxsNaZouIi9ikuOp2bCv3ekpXD9z2jwRtTRNXpvOOTGvUKCKvl1BAXHSzipYoQ9CSwJ9930Pk1f35vTu+WYfT40WDo0FHAvbyOwSLCalt48xZ7oHqMeZPHMC2OVQv7VKvUWrqhUM/AyYkJRuyM6Mq52pFHkg+h7ZXa4Hpc3a0PATCikIPaMByAo3XTH8sVEpPX8LnuDBoTnvDb6gP+n7S3iirJy8Wc6tAXniaGlIlQMcNos8G2Bg10IjxDUbRG6+uCy2CSzY0XrjNptxS/WiCYXN4LFdAog/O601f9ZmUrwS1QMmNuofR11UjK5chhIRXsNqwjvlbYJbxwILOx4CDENcM3KmXljGmGwmFfCB7BlCglZSBRHsxxOiSPMtqMvFHi30i8kxsBKMZp5sIE0W/ni7pN0g1jf/lr49D7NSjFGT503hPlpnFRrCfuqPI2V96xVs8Z7YsZWQqlsvpStNIowDBCNLbVa1le4a5xHsMr/E97WB8C8gVsFaY4qjDrsgD6a5+UpCwChEFEozkGkpbWwgQgvMo+FmC9XK4RnhZEfxaP2tUKVwOqDEHkXvDf3u85K6KD5VHU/i3Fl9Wup/pPXPrU6s5LXPPgIocZg=
  app: vitae-server
  on:
    repo: jrmmendes/vitae-server
    branch: main
  skip_cleanup: 'true'
