language: node_js
node_js:
- 12
cache:
  yarn: true
install:
- yarn --frozen-lockfile
before_script:
- curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64
  > ./cc-test-reporter
- chmod +x ./cc-test-reporter
- "./cc-test-reporter before-build"
script:
- yarn test:cov
- yarn test:e2e --forceExit
after_script:
- "./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT"
deploy:
  provider: heroku
  app:
    main: vitae-backend
  api_key:
    secure: DPVpVCkjRxma2J9ItvUkZ42kmAbMJ/bxMcqu8M8Q8agPecWyzQF4BEWB17rV/RGvq1bHL7FO1sQXhAgOECY4YPAxTyqWkbXYsnnKmWL5gllWlMPMldVySeT1TbB3d0f6Fch+vcuTBNP0mJoZ2W5GnXFjkBoLA6as3iqDTAh13yfI6UahNUetbcSsYjFFrn8KxuZAloz4ItYmmAOUCEYHrl/jV7/yR8nCU61LAsQ3YQDJE1/KesfWh1/4l0VaNkzrdYy69lWmN7V3U9CivGjuK7boHSiTDUIL0yboF4iyV/H1USrJm1GjUrgxYfDPrhjrcUwXm5wblJ6ZgkU99WTyUmovxZbZ95N/OnxSuZ/tkkVEQyfgEu9JSuB5kBq0eBgZJV18D9UmMrvtqncsHe7n3EAAYbL7T1iT0bJ2UV/y//UedbxzgXOCOVljLxZ7PfW6U/GWZpBE8FOvCsjeWi1o3jw6ep7uJ2S/i4JdAKrVGmYPaWJLdPWeBO+XogwEPQeEh/ZTj2J1C1qI1mm0KFQbSmxb/pebIurCHUNI36EasFHHf0Kq/Snu8h6bT2Nxqhx/cw9t0XLlvJ9tcWn4+RnaB3z0Atn+VRkhvh6CR4aks6il2YFgYQLAYtooePd3fI8Jl/8S6fwJezxaYwv+3oIM8x8LxTyJrgp11kF9m8+7MDM=
