language: node_js
node_js:
- 12
cache:
  yarn: true
install:
- yarn --frozen-lockfile
before_script:
- curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64
  > ./cc-test-reporter
- chmod +x ./cc-test-reporter
- "./cc-test-reporter before-build"
script:
- yarn test:cov
- yarn test:e2e --forceExit
after_script:
- "./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT"
deploy:
  provider: heroku
  app:
    main: vitae-backend
  api_key:
    secure: B+S/U1GDMNRxqj1JCu1/GWtqJtt4hBZD1DK2hJ0YF9M+vBFS3ljFKQYVvr44xUhyV0sqxu0MQoNzjus3PASGr8qBZmuNkrfiVHaNwmL5nik0M5QhZUFYiFJZ1kEJqMErqA4CgqMY+l5KbdzpKh8DcD1V11vV8hRqFsdvTJgt9m4KXu2lcrj44HdLY/ZHNTrDN1howH4qDNhr/TJMv4JV9lw2FAOLf7lySEXdpe/WxUQnGl31sBsBuvmlfyKVkUf5tQ6AEYlqcb/FgsbuxGDaiCmIeK60YxYgCBZy43/dZ1DTlRVv6Wnn0/0UrqWRghzcexb6mlAdvMclJWpZ+jXJ4jdPGNtP4plEU/1rbOLtY+PPG/jLpTbLqYidnMsimWBx2oAoUUGYI8JoAFrFMr0pvXSAzqweaJZC8oQcUimAnYn2+folqcGZi12FJcpRhR1D1S2sdzYRXxgcoRjexzovZfVBqMC2aXIteMdi+67LtpNp23vlWgkO+ZjSR8c/B9yyGuhCg2I7YBs6klFTLX+ik+nNQ2OBeRz+zdSDl69rhyt6BHcv96UBWxWjbyTvU3kq0EekuffYjGz4EzVNmnVhm9Q3/nhM4Yz4flIOgPQeGDaGwrw9ytZjqYoR2JRZ7BDdRBgsjmb4qrnccUcdFmdLh7J9L8LMExDnc7p3QCXWvNk=
