language: node_js
node_js:
- 12
cache:
  yarn: true
install:
- yarn --frozen-lockfile
before_script:
- curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64
  > ./cc-test-reporter
- chmod +x ./cc-test-reporter
- "./cc-test-reporter before-build"
script:
- yarn test:cov
- yarn test:e2e --forceExit
after_script:
- "./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT"
deploy:
  provider: heroku
  app:
    main: vitae-backend
  api_key:
    secure: V+CARcLpSzHiCpL0ZauV3sFs1RJlSYxDri1YbZ5eYUiCM7AWuT7LaDlEGHIuTdN2QDs4Xso8to7i1EyC8TyBYGCWJpr5NLHeYvdr7EqvLCLHn1xGig4QfcMDfXo5t48urTHkO7gnVfvnntXnxLQquDWYwjL3xwHUESJWETl5IuNpZeYY17g6QSREL1dZunc8ThPdVavMe+TSIfr/m82jG9qzJ9NpdBGGdh1OVGi9EtR3YlfuDmHgdZ52Wjxd5dwm6eoPd7su4uvxT+CWEiVWN+4XI84ovCdBzZ275dynsl4jKUGZAo9xz0UZek8H5sA7tdZmJTflYvoLuWbp9ZQVn7D/ayMWc/XnQr8XlVASXt2bKA2DcrQjosSuEOG7UNLY4YnlucKi/vsTp8IM6/yroTC1I6bV2pPuBokp5VhLy9PgHTtriZADCXRhwaHadGfJm5afv6z5eXWYkZBTPKJCFW+BxtN1aKPj/vHsNnC6zNyv/Jbz0MX7Gc0162qvNBYb6isqHud/Dal9I/1E+0gHQjIHBNhWxx8ErSf30li9Yem+74z3owVz8Zo0EyLvtl58pn1tzP0k0YElwDxUWT2aCTahN7+ei3M4X6y4V6sxs46q9mJQdBSY3JChgQW85XnldLYPiDvN/NXimfIRwg/f74qpD1Qhse4R71H/5gtiHM4=
